# Build-time default control bindings. Override at:
# SD:/3ds/ros2_3ds_interface/controls.ini
publish_once=A
toggle_publishing=B
toggle_listener=Y
send_probe=X
exit=START
next_view=R
previous_view=L
next_item=DOWN
previous_item=UP
activate=A
back=B